// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Genetic = Collections['genetics']['schema']['_output']
export declare const genetics: Genetic[]
